name: news_test_task
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.0.13
  carousel_slider: ^4.2.1
  google_fonts: ^3.0.1
  flutter_bloc: ^7.3.1
  equatable: ^2.0.3
  get_it: ^7.2.0
  dio: ^4.0.4 
  get: ^4.3.8
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter 

  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/back.png
  #   - images/a_dot_ham.jpeg


